{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib-neoforge",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-neoforge-5.0.0.jar",
          "url": "kfflib-neoforge-5.0.0.jar",
          "size": 38959,
          "sha512": "44e26cbbad20c1660a3235ed93eec2e2b794628064b8ee5ea9a7a776b03ccef8711549539ead58cac318118655c6e3ac3fc973527f86aaf7d58b18a28cac24cc",
          "sha256": "deb628f456b3cbdae6e16a84da64486374c027f3fc499fd2fec1937d9e21e7e9",
          "sha1": "f9a6124e295d4604f2b4be46d472811bd0ac2b15",
          "md5": "b2c87aa9b91a93a503dfef75fefc7f86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "5.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-neoforge-5.0.0.jar",
          "url": "kfflib-neoforge-5.0.0.jar",
          "size": 38959,
          "sha512": "44e26cbbad20c1660a3235ed93eec2e2b794628064b8ee5ea9a7a776b03ccef8711549539ead58cac318118655c6e3ac3fc973527f86aaf7d58b18a28cac24cc",
          "sha256": "deb628f456b3cbdae6e16a84da64486374c027f3fc499fd2fec1937d9e21e7e9",
          "sha1": "f9a6124e295d4604f2b4be46d472811bd0ac2b15",
          "md5": "b2c87aa9b91a93a503dfef75fefc7f86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-neoforge-5.0.0-sources.jar",
          "url": "kfflib-neoforge-5.0.0-sources.jar",
          "size": 11989,
          "sha512": "4f393b7e14a7648e058fd706e9fae6863ccfab2689ebe27852cfc11a00691082be9f5e1fd4e6245e48e406d1bb6f55024326cbce9c8ce68be50cb304353586b1",
          "sha256": "4aca4a7f22947e1743cc285f46e8667a84a1a413c62a45caea5c32bc25de8f5c",
          "sha1": "06a8afd98f7dfaa0f54559617c55c94b95d1a3b6",
          "md5": "01f5876b01ca5801f2671a61406ec445"
        }
      ]
    }
  ]
}
