{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kotlinforforge-neoforge",
    "version": "5.3.0e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "5.3.0e"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib-neoforge",
          "version": {
            "requires": "5.3.0e"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod-neoforge",
          "version": {
            "requires": "5.3.0e"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "5.3.0e"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib-neoforge",
          "version": {
            "requires": "5.3.0e"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod-neoforge",
          "version": {
            "requires": "5.3.0e"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinforforge-neoforge-5.3.0e-all.jar",
          "url": "kotlinforforge-neoforge-5.3.0e-all.jar",
          "size": 5700882,
          "sha512": "e395e874f9155b943356cd54a0fe9bda131480f94f0555f353966554cb98ae953b060baad1f53f27c87ab440551decd4f35fbd80e7f52635eb6ac08440fda430",
          "sha256": "16ad305b0b8e3bb6e3ddfa4daa2ff36e6476c0f55332fc8bbc5b4dba189eddc4",
          "sha1": "fa1f9c1c4d0b7e749fb9e64be23d4ff46fd156d4",
          "md5": "c2af63004c5cda5f77948c9b2a018b20"
        }
      ]
    }
  ]
}
