{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kffmod-neoforge",
    "version": "5.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kffmod-neoforge-5.0.2.jar",
          "url": "kffmod-neoforge-5.0.2.jar",
          "size": 69806,
          "sha512": "8999a1d251ca705318d521cb96e3b4a931797514aeebfa234e7c5b8c1e90525596fee6b790b56faed29c01a650432038167670c2de3aed80e1e17310588e3d3a",
          "sha256": "3537395ac8bfad7f28df536c97da1711a009c0e95c518eebad1c4ab5f84df939",
          "sha1": "1210f733e493b43610ccdc35a16d1a819d03d580",
          "md5": "a322cce65c63023cd95f3f2decfcacd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "5.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib-neoforge",
          "version": {
            "requires": "5.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kffmod-neoforge-5.0.2.jar",
          "url": "kffmod-neoforge-5.0.2.jar",
          "size": 69806,
          "sha512": "8999a1d251ca705318d521cb96e3b4a931797514aeebfa234e7c5b8c1e90525596fee6b790b56faed29c01a650432038167670c2de3aed80e1e17310588e3d3a",
          "sha256": "3537395ac8bfad7f28df536c97da1711a009c0e95c518eebad1c4ab5f84df939",
          "sha1": "1210f733e493b43610ccdc35a16d1a819d03d580",
          "md5": "a322cce65c63023cd95f3f2decfcacd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kffmod-neoforge-5.0.2-sources.jar",
          "url": "kffmod-neoforge-5.0.2-sources.jar",
          "size": 69144,
          "sha512": "72b063a1b22e755fea5f813e6ce412c97557d9b7e906d6f809e8370db2032123b83b0eaaef9178d6140ac148f04dd49f2fd959e2495d558dfd378d1dc59d566d",
          "sha256": "2fec496fbcf98d3cf174873c0476150cf41cca4fee5dfc64651a27c0cf11f552",
          "sha1": "ea7ee1e82a754c26e1684d7ebf75460bc8e7b865",
          "md5": "943059333d44e5730a06b0aa2df4a238"
        }
      ]
    }
  ]
}
