{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib-neoforge",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-neoforge-5.1.0.jar",
          "url": "kfflib-neoforge-5.1.0.jar",
          "size": 38959,
          "sha512": "7d22ebaac8d0c9ca00765b52972474beb5523877bf8913ab54449adf5a0e30cd0edf1e116c9465d4f7edc6db7125b8fae9e720b47b8f64fca6230aff473a9864",
          "sha256": "29f3e6f346262ae101c1a428aebf6667b4ffb15cea1b25eed86cde6b50e30fc4",
          "sha1": "66a88eb700252c4d07cdfc62daecb8bca5b4a037",
          "md5": "326fcda84ddc2b7f24f5a4c5534bff9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "5.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-neoforge-5.1.0.jar",
          "url": "kfflib-neoforge-5.1.0.jar",
          "size": 38959,
          "sha512": "7d22ebaac8d0c9ca00765b52972474beb5523877bf8913ab54449adf5a0e30cd0edf1e116c9465d4f7edc6db7125b8fae9e720b47b8f64fca6230aff473a9864",
          "sha256": "29f3e6f346262ae101c1a428aebf6667b4ffb15cea1b25eed86cde6b50e30fc4",
          "sha1": "66a88eb700252c4d07cdfc62daecb8bca5b4a037",
          "md5": "326fcda84ddc2b7f24f5a4c5534bff9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-neoforge-5.1.0-sources.jar",
          "url": "kfflib-neoforge-5.1.0-sources.jar",
          "size": 11989,
          "sha512": "9fdd3f6fa1a7584bccf8ea39717dce4833816f4060b0bb022d76faf57721b839f3caece40778280ba9e6354e5990e218fe39a42c4070f67d5204bf1b4296b52a",
          "sha256": "e3507a99c6a539ec45a4d3aec7febd8383e0039442d1b0ba40fe1b97b1c4f34b",
          "sha1": "cbaf67113de4b180b2a8b20c7a582372bea1892d",
          "md5": "005037d6e1d9a5592f1ba3311a530bd1"
        }
      ]
    }
  ]
}
