{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib",
    "version": "4.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-4.11.0.jar",
          "url": "kfflib-4.11.0.jar",
          "size": 41653,
          "sha512": "47cd01258f789b4f08438fa2a752b87fef70b22eba5f6f297356aa78cfcc252aa2b1e90a4b77d2d4709487f78e3da220dd16537123850723a03957b9471ae2f9",
          "sha256": "5dfcc74a7f8d90bf3a73227b65745bf22eeaf2a7e94d05a5b0947f609bef1533",
          "sha1": "4fa4c8f9f8f09cc3da3166500dade61366f5516a",
          "md5": "3d1837451f4aac801c3615119d60f862"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflib-4.11.0.jar",
          "url": "kfflib-4.11.0.jar",
          "size": 41653,
          "sha512": "47cd01258f789b4f08438fa2a752b87fef70b22eba5f6f297356aa78cfcc252aa2b1e90a4b77d2d4709487f78e3da220dd16537123850723a03957b9471ae2f9",
          "sha256": "5dfcc74a7f8d90bf3a73227b65745bf22eeaf2a7e94d05a5b0947f609bef1533",
          "sha1": "4fa4c8f9f8f09cc3da3166500dade61366f5516a",
          "md5": "3d1837451f4aac801c3615119d60f862"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-4.11.0-sources.jar",
          "url": "kfflib-4.11.0-sources.jar",
          "size": 12566,
          "sha512": "5326cfec464e636f05c40ba9113d699dda7593c8794341a3260cb4610b120c0320b00d15fdb5cdca6c475d446e2cf0539ee8c7e1d5cbe17ec3ad96e8a8e5c258",
          "sha256": "8bf52f1cffc005f0506e770b2bd4beb92c92fb82028f40cbc1ad013bd6de66e1",
          "sha1": "8dca13931f5019e85a5055bd3d87b0e113011bab",
          "md5": "18d7d7c42aae1bb85fce50b4b9004885"
        }
      ]
    }
  ]
}
