{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kotlinforforge-neoforge",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib-neoforge",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod-neoforge",
          "version": {
            "requires": "5.0.1"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinforforge-neoforge-5.0.1-all.jar",
          "url": "kotlinforforge-neoforge-5.0.1-all.jar",
          "size": 7290516,
          "sha512": "7ef76b4a2bf783802906da2ee4081d4871515c1194d4c0908b4dfe4b237f8d0be1bdbf672f52b4894bbf010eb9d2ad5342640e35db445abd39009ea7fb47121e",
          "sha256": "11849ca2b505dabb8af700c766156c46b2fbb111bf60c25f8134e73d09ecc068",
          "sha1": "cbe5d88670c6856b72604942a6e3cc492166e468",
          "md5": "46769728628f4a749bae79380fe4adf4"
        }
      ]
    }
  ]
}
