{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflang-neoforge",
    "version": "5.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-neoforge-5.3.0.jar",
          "url": "kfflang-neoforge-5.3.0.jar",
          "size": 20421,
          "sha512": "3aa15427cd16c6b98b593b72b42d2f78afd219ff8c3c84eea21e3597296f462a1c03360adbc513274a1b12ce5ae4254d8d15dd4f2cddb43c826dc0dfab957ac4",
          "sha256": "1dda9830315e8586e34dba6489e21311abd7526db98aaeee4975d0a55111c638",
          "sha1": "0493d19ee691e949542be03546a61db9e20ab02f",
          "md5": "10d813c230a57997edfad8fb16e1fa05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "[3,5)"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-neoforge-5.3.0.jar",
          "url": "kfflang-neoforge-5.3.0.jar",
          "size": 20421,
          "sha512": "3aa15427cd16c6b98b593b72b42d2f78afd219ff8c3c84eea21e3597296f462a1c03360adbc513274a1b12ce5ae4254d8d15dd4f2cddb43c826dc0dfab957ac4",
          "sha256": "1dda9830315e8586e34dba6489e21311abd7526db98aaeee4975d0a55111c638",
          "sha1": "0493d19ee691e949542be03546a61db9e20ab02f",
          "md5": "10d813c230a57997edfad8fb16e1fa05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflang-neoforge-5.3.0-sources.jar",
          "url": "kfflang-neoforge-5.3.0-sources.jar",
          "size": 6914,
          "sha512": "b0c979941281b09d8c19286395198d3dd9038515c47e11557af9086d7bbe3e88af7b9ae80be66982e3e96b6db24dcef94c25517a2dccceab13821348f5006927",
          "sha256": "e9b4965d812eb0e052f8111c4082e82daa42c4951abc6c9068be1dff08c8e88b",
          "sha1": "9142b29856276897e495f202934e823244129978",
          "md5": "322bcc82100e5075eecf98883d5de472"
        }
      ]
    }
  ]
}
