{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflib-neoforge",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-neoforge-5.0.1.jar",
          "url": "kfflib-neoforge-5.0.1.jar",
          "size": 38959,
          "sha512": "e961b8877008781d1d3b5ca2557fa6f66faf423cf36ac2c4b6d7bffacac9e717838e89aad207d23e3b15d45b128c253345b457d2fcbffb13979fae77d86d340c",
          "sha256": "9fe54cb670aa7afd35a4a8dd2dd355ab90498e4d0d60e69719826dab393e7558",
          "sha1": "80433d4eea5ae81b120870f3e7f12bbc7246a051",
          "md5": "7cea9428469a834a7b0a26420880a474"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "5.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "kfflib-neoforge-5.0.1.jar",
          "url": "kfflib-neoforge-5.0.1.jar",
          "size": 38959,
          "sha512": "e961b8877008781d1d3b5ca2557fa6f66faf423cf36ac2c4b6d7bffacac9e717838e89aad207d23e3b15d45b128c253345b457d2fcbffb13979fae77d86d340c",
          "sha256": "9fe54cb670aa7afd35a4a8dd2dd355ab90498e4d0d60e69719826dab393e7558",
          "sha1": "80433d4eea5ae81b120870f3e7f12bbc7246a051",
          "md5": "7cea9428469a834a7b0a26420880a474"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflib-neoforge-5.0.1-sources.jar",
          "url": "kfflib-neoforge-5.0.1-sources.jar",
          "size": 11989,
          "sha512": "69ef20b40f282687bcce448b172e29bf3fae312ecb399ca8584af904460385f42c26505d5740344c20a1a682140c0d49e459e377ebce505fe3c492837b669e6a",
          "sha256": "886b2666ff7e99dc0d6c5e1cbc55c708fde6186121cfc3b31ad5010b89176e0a",
          "sha1": "87c2b0d1fdb18f4c0a38e5db32e465600c4b0eca",
          "md5": "e181e19e2b8852e717662e2284ee4777"
        }
      ]
    }
  ]
}
