{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kotlinforforge-neoforge",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang-neoforge",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib-neoforge",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod-neoforge",
          "version": {
            "requires": "5.1.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinforforge-neoforge-5.1.0-all.jar",
          "url": "kotlinforforge-neoforge-5.1.0-all.jar",
          "size": 7290514,
          "sha512": "ab89284566835cd8c57ce805a4e370f48ec37d9f2496cdb36ca77b8c674ddfb7590bbe58c5c012ae1edf9ed0c357b7d20c5ecd2bdbb22267837c9b2e0d425bcb",
          "sha256": "4e4504dba2bbd488e1f2a54ac9c15fffb2ffeaf95890ea5a39810de8ee5406ef",
          "sha1": "fddac9ef392eca995714e4b56e4aab90af30f926",
          "md5": "fe51cfb7b81d58e05c290e7c5a7aa774"
        }
      ]
    }
  ]
}
